import '@/lib/server/only';
/**
 * COPILOT CONTEXT BOUNDARY — ARCHITECTURE §8.1 and §8.3.
 *
 * This is the only thing the management copilot may ever be told about the business. It
 * is built before the copilot for the same reason `guard.ts` was built before the model
 * call: once a prompt assembler exists, "what can the assistant see" becomes a question
 * about whichever fields somebody happened to spread into a template. Answering it now,
 * as a whitelist with tests, costs nothing and is the whole security property.
 *
 * Three rules shape everything below.
 *
 * **A whitelist, never a blacklist.** §8.1 names the copilot's tools —
 * `getKpis · getPropertyPerformance · getExpenseBreakdown · getPlatformMix · getAlerts` —
 * and §8.3 names what each context sees. A tool that is not in `COPILOT_TOOLS` does not
 * exist here, and every field of every projection is written out by hand. Spreading a
 * view object would mean a field added upstream next year silently joins the context.
 *
 * **Each tool inherits the capability that already guards its data.** §8.1's diagram
 * draws the tools straight onto `Repositories`; that half of it does not survive contact
 * with the rest of the architecture, because §1.1's fifth principle puts every derived
 * number in one place and Decision D1 keeps the read path off `AnalyticsRepository`
 * altogether. So a tool projects an endpoint the application already serves, and takes
 * that endpoint's capability from the route registry rather than declaring its own. One
 * definition, and a copilot answer can never exceed what its caller could have read by
 * opening the screen.
 *
 * **The model is told, never asked.** Every figure here is computed by the deterministic
 * engines. §8.2's fourth rule — "forecasts are never generated by the model" — is why
 * the forecast projection carries its `ESTIMATE` label, its method and its confidence:
 * the assistant's whole job is to explain a number that already exists.
 *
 * Nothing in this module calls a model, reads a key or opens a socket, and it is wired to
 * no route. AI arrives in Phase 9; the boundary it must pass through arrives here.
 */
import { findRoute } from '@/lib/server/api/routes';
import { capabilitiesFor, type Capability, type Role } from '@/lib/server/auth/roles';
import { buildAiPayload, type AiPayload } from '@/lib/server/ai/guard';
import type { ResolvedEnvironment } from '@/lib/server/environment/config';
import { PNL as PNL_CONTRACT } from '@/lib/contract/contract.generated';
import type {
  DashboardDataProvider, ReportFilters, KpiFormat, UrgentSeverity,
} from '@/lib/data/providers/types';

/* ------------------------------------------------------------------ *
 * The tool registry
 * ------------------------------------------------------------------ */

export type CopilotToolName =
  | 'getKpis'
  | 'getPropertyPerformance'
  | 'getExpenseBreakdown'
  | 'getPlatformMix'
  | 'getAlerts'
  | 'getForecast'
  | 'getCashFlowForecast';

export interface CopilotToolDefinition {
  name: CopilotToolName;
  /** The guarded endpoint this tool projects. Its capability IS the tool's capability. */
  route: string;
  summary: string;
}

/**
 * §8.1's five copilot tools, plus the two forecast reads §8.2's fourth rule requires.
 *
 * The forecast pair is not an addition to §8.1's list so much as its precondition: a
 * model that may explain a deterministic forecast but never produce one has to be handed
 * the deterministic forecast. They are split in two because the architecture already
 * splits them — a projected cash balance is a cash figure and carries `cashflow.read`,
 * not `analytics.read`.
 *
 * `getExpenseBreakdown` deserves a word. §8.3 forbids the copilot raw ledgers, so this
 * cannot be `getExpenses`, which returns ledger rows. It is the P&L's operating-expense
 * lines, categorised by the generated contract's own V1 mapping — an aggregate, and the
 * same one the P&L screen shows.
 */
export const COPILOT_TOOLS: readonly CopilotToolDefinition[] = [
  { name: 'getKpis', route: '/api/analytics/dashboard',
    summary: 'Headline KPIs for the period' },
  { name: 'getPropertyPerformance', route: '/api/analytics/by-property',
    summary: 'Per-property revenue, cost, profit and occupancy' },
  { name: 'getExpenseBreakdown', route: '/api/pnl',
    summary: 'Operating expenses by P&L category for the period' },
  { name: 'getPlatformMix', route: '/api/analytics/by-platform',
    summary: 'Bookings and net revenue by platform' },
  { name: 'getAlerts', route: '/api/analytics/alerts',
    summary: 'Operational alerts, most pressing first' },
  { name: 'getForecast', route: '/api/forecast/occupancy',
    summary: 'Deterministic occupancy and revenue estimates for the month ahead' },
  { name: 'getCashFlowForecast', route: '/api/forecast/cashflow',
    summary: 'Deterministic projected closing cash balance for the month ahead' },
];

/**
 * The capability a tool requires — resolved from the route registry, never restated.
 *
 * A tool naming a route that does not exist is a programming error worth failing on at
 * import time: silently granting it "no capability" would make it reachable by everyone.
 */
export function capabilityForTool(tool: CopilotToolDefinition): Capability {
  const route = findRoute('GET', tool.route);
  if (!route) {
    throw new Error(`Copilot tool ${tool.name} projects an unregistered route: ${tool.route}`);
  }
  return route.capability;
}

/** Holding one of these is what makes a caller a copilot caller at all (§7). */
export const COPILOT_CAPABILITIES: readonly Capability[] = ['ai.copilot', 'ai.operations'];

export class CopilotNotPermittedError extends Error {
  constructor(role: Role) {
    super(
      `The ${role} role holds no copilot capability. A context is not assembled for a ` +
      'caller who may not ask, so there is no payload to leak if the route were ever ' +
      'reached without its guard.',
    );
    this.name = 'CopilotNotPermittedError';
  }
}

/* ------------------------------------------------------------------ *
 * The projections — every field written out, none spread
 * ------------------------------------------------------------------ */

export interface CopilotKpi {
  key: string;
  label: string;
  /** Meaningless when `unavailable` is set; the model is told which, never left to guess. */
  value: number;
  format: KpiFormat;
  changeRatio: number | null;
  /** §8.2's third rule: "no data" is a required answer, so it must survive into context. */
  unavailable: { reason: string; message: string } | null;
}

export interface CopilotPropertyMetrics {
  propertyId: string;
  unit: string;
  netRevenue: number;
  directOperatingExpenses: number;
  profit: number;
  occupiedNights: number;
  availableNights: number;
  occupancyPct: number;
  adr: number;
  revPar: number;
  bookings: number;
}

export interface CopilotExpenseLine {
  key: string;
  label: string;
  amount: number;
}

export interface CopilotExpenseBreakdown {
  monthKey: string;
  lines: readonly CopilotExpenseLine[];
  total: number;
}

export interface CopilotPlatformMix {
  platform: string;
  bookings: number;
  grossRevenue: number;
  feesAndDeductions: number;
  netRevenue: number;
  shareOfNetRevenue: number;
}

/**
 * §8.3's "alert summaries" — the operations alert with its guest name removed.
 *
 * `severity`, `propertyId`, `reference` and `action` are structured or application-authored
 * and carry nothing about a person. `summary` is the board's title, which interpolates
 * workbook text and, for an arrival, the guest's minimised display name. §8.3 is explicit
 * that "guest names are stripped from copilot context by default", so they are stripped
 * here rather than at the API — the alerts endpoint is correct for the operations screen
 * it serves, and a management assistant is a different consumer with a stricter rule.
 */
export interface CopilotAlert {
  severity: UrgentSeverity;
  propertyId: string;
  reference: string;
  summary: string;
  action: string;
}

/**
 * A §9 estimate as the copilot may see it: the number, and everything needed to say where
 * it came from. No `inputs` block — the model does not need the working to explain the
 * result, and every field omitted is a field that cannot be re-derived into a new figure.
 */
export interface CopilotForecast {
  horizon: string;
  monthKey: string;
  status: string;
  /** Constant 'ESTIMATE' by §9. Present so an answer cannot describe it as anything else. */
  label: string;
  method: string;
  value: number | null;
  unit: string;
  confidence: string | null;
  /** Present only when the estimate is INSUFFICIENT_DATA. */
  reason: string | null;
}

/** A tool the caller's role does not reach, and the capability that would grant it. */
export interface CopilotOmission {
  tool: CopilotToolName;
  capability: Capability;
  message: string;
}

/**
 * Everything the copilot is allowed to know for one question.
 *
 * A field is null when its tool was not run — either the role does not hold the
 * capability, or the period carries nothing to report. Null means "not in context",
 * which §8.2's third rule requires the assistant to say aloud rather than fill in.
 */
export interface CopilotContext {
  /** The period every figure describes. §8.2's second rule makes this mandatory. */
  period: string;
  /** Where the figures came from, so an answer can cite provenance. */
  source: string;
  asOf: string;
  kpis: readonly CopilotKpi[] | null;
  propertyPerformance: readonly CopilotPropertyMetrics[] | null;
  expenseBreakdown: CopilotExpenseBreakdown | null;
  platformMix: readonly CopilotPlatformMix[] | null;
  alerts: readonly CopilotAlert[] | null;
  forecast: readonly CopilotForecast[] | null;
  /** The tools that ran, so an answer can name its sources. */
  tools: readonly CopilotToolName[];
  omitted: readonly CopilotOmission[];
}

/* ------------------------------------------------------------------ *
 * Guest-name removal (§8.3)
 * ------------------------------------------------------------------ */

const GUEST_PLACEHOLDER = '[guest]';

const escapeForRegExp = (value: string): string => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

/**
 * Remove the named guests from a line of free text.
 *
 * Enumerated rather than pattern-matched: the names come from the same operations board
 * the text came from, so this removes exactly the strings that were interpolated into it
 * rather than guessing which capitalised words are people. Guessing would both miss names
 * and redact property names, and a redaction that eats the subject of the sentence makes
 * the alert useless.
 *
 * Longest first, so "Priya M." is removed whole rather than leaving a stray initial
 * behind after a shorter name matched inside it.
 */
export function stripGuestNames(text: string, names: readonly string[]): string {
  const ordered = [...new Set(names.filter((n) => n.trim() !== ''))]
    .sort((a, b) => b.length - a.length);
  return ordered.reduce(
    (out, name) => out.replace(new RegExp(escapeForRegExp(name), 'g'), GUEST_PLACEHOLDER),
    text,
  );
}

/* ------------------------------------------------------------------ *
 * Immutability
 * ------------------------------------------------------------------ */

/**
 * Freeze the assembled context, all the way down.
 *
 * §8.1's tools are read-only by construction — the provider interface has no writer and
 * mutations travel a different path entirely. Freezing makes that structural rather than
 * conventional: a future prompt assembler that tried to annotate a figure in place would
 * throw here instead of quietly editing the business's numbers on their way to a model.
 */
function deepFreeze<T>(value: T): T {
  if (value === null || typeof value !== 'object' || Object.isFrozen(value)) return value;
  for (const key of Object.getOwnPropertyNames(value)) {
    deepFreeze((value as Record<string, unknown>)[key]);
  }
  return Object.freeze(value);
}

/* ------------------------------------------------------------------ *
 * Assembly
 * ------------------------------------------------------------------ */

const EXPENSE_LINE_KEYS: readonly string[] = [
  ...Object.keys(PNL_CONTRACT.expenseLines), 'otherOperating',
];

export interface CopilotContextOptions {
  role: Role;
  resolved?: ResolvedEnvironment;
  now?: Date;
}

/**
 * Assemble the copilot's context for one question.
 *
 * The provider is the same one the screens use, so the assistant and the operator read
 * one computation. Only the whitelisted reads are called: a test proxies the provider and
 * asserts that the set of methods this function touches is exactly the tool list, which is
 * what makes "arbitrary workbook access is impossible" a measured fact rather than a claim.
 *
 * The result is stamped by `buildAiPayload`, so a context built against the demonstration
 * workbook can never be dispatched to a production model — and, in this phase, cannot be
 * dispatched at all.
 */
export async function buildCopilotContext(
  provider: DashboardDataProvider,
  filters: ReportFilters,
  options: CopilotContextOptions,
): Promise<AiPayload<CopilotContext>> {
  const held = capabilitiesFor(options.role);
  if (!COPILOT_CAPABILITIES.some((c) => held.includes(c))) {
    throw new CopilotNotPermittedError(options.role);
  }

  const granted: CopilotToolName[] = [];
  const omitted: CopilotOmission[] = [];
  for (const tool of COPILOT_TOOLS) {
    const capability = capabilityForTool(tool);
    if (held.includes(capability)) granted.push(tool.name);
    else {
      omitted.push({
        tool: tool.name,
        capability,
        message: `Not available to this role — ${tool.summary.toLowerCase()} requires ${capability}.`,
      });
    }
  }
  const may = (name: CopilotToolName) => granted.includes(name);

  /*
   * The dashboard read serves two tools, and the operations read serves one. Each is
   * performed only when a tool that needs it was granted, so a role's context costs it
   * no read it was not entitled to make.
   */
  const dashboard = may('getKpis') || may('getPlatformMix')
    ? await provider.getDashboard(filters) : null;
  const properties = may('getPropertyPerformance') ? await provider.getProperties(filters) : null;
  const pnl = may('getExpenseBreakdown') ? await provider.getPnl(filters) : null;
  const operations = may('getAlerts') ? await provider.getOperations(filters) : null;
  const forecastView = may('getForecast') || may('getCashFlowForecast')
    ? await provider.getForecast(filters) : null;

  const meta = dashboard?.meta ?? properties?.meta ?? pnl?.meta
    ?? operations?.meta ?? forecastView?.meta ?? await provider.getSourceMeta();

  const kpis: CopilotKpi[] | null = dashboard && may('getKpis')
    ? dashboard.data.kpis.map((k) => ({
      key: k.key,
      label: k.label,
      value: k.value,
      format: k.format,
      changeRatio: k.changeRatio ?? null,
      unavailable: k.unavailable
        ? { reason: k.unavailable.reason, message: k.unavailable.message }
        : null,
    }))
    : null;

  const propertyPerformance: CopilotPropertyMetrics[] | null = properties
    ? properties.data.map((p) => ({
      propertyId: p.propertyId,
      unit: p.unit,
      netRevenue: p.netRevenue,
      directOperatingExpenses: p.directOperatingExpenses,
      profit: p.profit,
      occupiedNights: p.occupiedNights,
      availableNights: p.availableNights,
      occupancyPct: p.occupancyPct,
      adr: p.adr,
      revPar: p.revPar,
      bookings: p.bookings,
    }))
    : null;

  /*
   * The P&L is a 12-month block; the copilot is answering about one period. The month's
   * column is taken out of it, and when the P&L has no column for that month — it omits
   * months that traded nothing — the breakdown is null rather than a table of zeroes.
   */
  let expenseBreakdown: CopilotExpenseBreakdown | null = null;
  if (pnl) {
    const index = pnl.data.months.indexOf(filters.month);
    if (index >= 0) {
      const lines = pnl.data.lines
        .filter((line) => EXPENSE_LINE_KEYS.includes(line.key))
        .map((line) => ({ key: line.key, label: line.label, amount: line.values[index] ?? 0 }));
      const total = pnl.data.lines.find((line) => line.key === 'totalOpex')?.values[index] ?? 0;
      expenseBreakdown = { monthKey: filters.month, lines, total };
    }
  }

  const platformMix: CopilotPlatformMix[] | null = dashboard && may('getPlatformMix')
    ? dashboard.data.platforms.map((p) => ({
      platform: p.platform,
      bookings: p.bookings,
      grossRevenue: p.grossRevenue,
      feesAndDeductions: p.feesAndDeductions,
      netRevenue: p.netRevenue,
      shareOfNetRevenue: p.shareOfNetRevenue,
    }))
    : null;

  let alerts: CopilotAlert[] | null = null;
  if (operations) {
    // Every guest the board names today, gathered from the structured rows so the removal
    // below is an exact match rather than a heuristic.
    const guestNames = [...operations.data.arrivals, ...operations.data.departures]
      .map((row) => row.guestDisplayName);
    alerts = operations.data.urgent.map((item) => ({
      severity: item.severity,
      propertyId: item.propertyId,
      reference: item.reference,
      summary: stripGuestNames(item.title, guestNames),
      action: item.action,
    }));
  }

  let forecast: CopilotForecast[] | null = null;
  if (forecastView) {
    const project = (e: {
      horizon: string; monthKey: string; status: string; label: string; method: string;
      value: number | null; unit: string; reason: string | null;
      confidence: { level: string | null };
    }): CopilotForecast => ({
      horizon: e.horizon,
      monthKey: e.monthKey,
      status: e.status,
      label: e.label,
      method: e.method,
      value: e.value,
      unit: e.unit,
      confidence: e.confidence.level,
      reason: e.reason,
    });
    forecast = [
      ...(may('getForecast')
        ? [project(forecastView.data.occupancy), project(forecastView.data.revenue)] : []),
      ...(may('getCashFlowForecast') ? [project(forecastView.data.cashflow)] : []),
    ];
  }

  const context: CopilotContext = {
    period: meta.period,
    source: meta.source,
    asOf: meta.asOf,
    kpis,
    propertyPerformance,
    expenseBreakdown,
    platformMix,
    alerts,
    forecast,
    tools: granted,
    omitted,
  };

  return buildAiPayload(deepFreeze(context), {
    resolved: options.resolved,
    now: options.now,
  });
}
